import './js/mobile-menu';
import './js/buy-now';
import './js/popup';
import './js/our-products';
import './js/reviews';
import './js/subscribe';
import "./js/rewiews-modal"
import "./js/popup-review"
import "./js/video"